-- CreateTable
CREATE TABLE `Ticketing` (
    `UUID_TC` VARCHAR(191) NOT NULL,
    `UUID_UA` VARCHAR(191) NOT NULL,
    `DateTime_TC` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `Nomor_TC` VARCHAR(191) NOT NULL,
    `Status_TC` BOOLEAN NOT NULL,

    PRIMARY KEY (`UUID_TC`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Ticketing` ADD CONSTRAINT `Ticketing_UUID_UA_fkey` FOREIGN KEY (`UUID_UA`) REFERENCES `UserAccount`(`UUID_UA`) ON DELETE RESTRICT ON UPDATE CASCADE;
