-- CreateTable
CREATE TABLE `UserAccount` (
    `UUID_UA` VARCHAR(191) NOT NULL,
    `Name_UA` VARCHAR(191) NOT NULL,
    `Email_UA` VARCHAR(191) NOT NULL,
    `Password_UA` VARCHAR(191) NOT NULL,
    `Phone_UA` VARCHAR(191) NOT NULL,
    `Photo_UA` VARCHAR(191) NULL,
    `NIK_UA` VARCHAR(191) NULL,
    `NIP_UA` VARCHAR(191) NULL,
    `isPasien_UA` BOOLEAN NOT NULL DEFAULT true,
    `isOfficer_UA` BOOLEAN NOT NULL DEFAULT false,
    `isActive_UA` BOOLEAN NOT NULL DEFAULT true,
    `LastLogin_UA` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `UserAccount_Email_UA_key`(`Email_UA`),
    PRIMARY KEY (`UUID_UA`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `DataMedis` (
    `UUID_DM` VARCHAR(191) NOT NULL,
    `UUID_UA` VARCHAR(191) NOT NULL,
    `Diagnosis_DM` VARCHAR(191) NULL,
    `Obat_DM` VARCHAR(191) NULL,
    `Alergi_DM` VARCHAR(191) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`UUID_DM`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `DataMedis` ADD CONSTRAINT `DataMedis_UUID_UA_fkey` FOREIGN KEY (`UUID_UA`) REFERENCES `UserAccount`(`UUID_UA`) ON DELETE RESTRICT ON UPDATE CASCADE;
